# Generated by Django 4.2.1 on 2023-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockorder',
            name='side',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
        migrations.AddField(
            model_name='mockorder',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='market', max_length=4),
        ),
    ]
