# Generated by Django 4.2.1 on 2023-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('meal', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
