# Generated by Django 4.2.1 on 2023-05-11 10:50

import commentVerification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentValidationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('validation_state', models.CharField(choices=[(commentVerification.models.ValidationState['COULD_NOT_VALIDATE'], 'could_not_validate'), (commentVerification.models.ValidationState['ACCEPTED'], 'accepted'), (commentVerification.models.ValidationState['REJECTED'], 'rejected')], max_length=20)),
            ],
            options={
                'ordering': ['comment_body'],
            },
        ),
    ]
