name: Deploy-Backend-to-Compute-Engine

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'
      - '.github/workflows/backend-deploy.yml'

      
jobs:
  deploy:
    name: Deploy to Compute Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: 34.105.66.254
          REMOTE_USER: alp.tuna.453
          SOURCE: app/backend/
          TARGET: ~/backend
          ARGS: --delete
          EXCLUDE: .env
          SCRIPT_AFTER: |
            cd ~/backend
            docker build -t pollup:backend .
            docker stop app
            docker rm app
            docker run --name app -p 1923:3000 -d pollup:backend
